### ISSUE TITLE
Adding a new ADT type `These`

### ISSUE THREAD

**Issue by DengYiping** [HubSpot/algebra#30]
Currently, I have implemented a `These` type in Java, and believe it could be useful to include it in `algebra` library. 

Idea comes from: https://hackage.haskell.org/package/these

@stevegutz If you find it useful, I can open a PR here to make a change.

**Comment by stevegutz** [comment]
Can you please more of what you mean? Would this be a result that has both an error and an ok value?

**Comment by DengYiping** [comment]
Yes, exactly. The naming is not exactly `ok` and `error` but more of `left` and `right`.

**Comment by stevegutz** [comment]
This seems like a case for not using `Result` and instead returning your own type. Or returning a `Result<SomeType, ErrorType>`. 

I'd also generally recommend making your own models with labeled fields rather than using generic types like `Pair`, `Either`, or `These`. It makes generally makes the code much more clear and readable.
